name: voice-live-agent
metadata:
  template: voice-live-agent@0.1.0
requiredVersions:
  azd: ">=1.14.0"
services:
    app:
        project: server
        host: appservice
        language: python
pipeline:
  variables:
    - AZURE_LOCATION
    - AZURE_RESOURCE_GROUP
    - AZURE_APP_SERVICE_NAME
    - AZURE_APP_SERVICE_URL
    - SERVICE_API_ENDPOINTS
    - AZURE_VOICE_LIVE_ENDPOINT